export const images = {
    home: require("../assets/images/home.png"),
    star: require("../assets/icons/star.png"),
    logo: require("../assets/images/sda_logo.png"),
    menu: require("../assets/images/menu.png"),
    x: require("../assets/images/x.png"),
    about: require("../assets/images/about.png"),
    dark: require("../assets/images/cresent.png"),
    settings: require("../assets/images/settings.png"),
    sun: require("../assets/images/sun.png"),
    searchn: require("../assets/images/searchn.png"),
    fontsize: require("../assets/images/fontsize.png"),
    reset: require("../assets/images/reset.png"),
    update: require("../assets/images/update.png"),
    clock: require("../assets/images/clock.png"),
    bell: require("../assets/images/bell.png"),
    rate: require("../assets/images/rate.png"),
    lesson1: require("../assets/images/lesson1.png"),
    lesson2: require("../assets/images/lesson2.png"),
    lesson3: require("../assets/images/lesson3.png"),
    lesson4: require("../assets/images/lesson44.png"),
    table: require("../assets/images/table.png"),
    question: require("../assets/images/question.png"),
    options: require("../assets/images/options.png"),
    share: require("../assets/images/share.png"),
}